### ISSUE TITLE
Unable to Load Distributed Tracing Blade

### ISSUE THREAD

**Issue by 1openwindow** [Azure/Azure-Spring-Cloud#1]
**Describe the bug**
Unable to Load Distributed Tracing Blade

![unabletoload](https://user-images.githubusercontent.com/26411726/67449927-668e6200-f64e-11e9-85a1-c88ed47b4e61.png)

**To Reproduce**
don't know to reproduce it.

**Comment by xscript** [comment]
Duplicate of #6
